package com.neevtech.jaxb.model.territorymanager;

import java.sql.Date;

public class All {

	private long terrId;
	private String createdBy;
	private Date creationDate;
	private String lastUpdatedBy;
	private Date lastUpdatedDate;
	private boolean lastUpdatedLogin;
	private long requestId;
	private long programApplicationId;
	private long programId;
	private Date programUpdateDate;
	private String applicationShortName;
	private String name;
	private boolean enabledFlag;
	private boolean startDateActive;
	private boolean endDateActive;
	private boolean plannedFlag;
	private long parentTerritoryId;
	private long territoryTypeId;
	private long templateTerritoryId;
	private boolean templateFlag;
	private long escalationTerritoryId;
	private boolean escalationTerritoryFlag;
	private boolean allowOverlapFlag;
	private int rank;
	private String description;
	private boolean updateFlag;
	private boolean autoAssignResourceFlag;
	private String attributeCategory;
	private String attribute1;
	private String attribute2;
	private String attribute3;
	private String attribute4;
	private String attribute5;
	private String attribute6;
	private String attribute7;
	private String attribute8;
	private String attribute9;
	private String attribute10;
	private String attribute11;
	private String attribute12;
	private String attribute13;
	private String attribute14;
	private String attribute15;
	private long orgId;
	private long securityGroupId;
	private String origSystemReference;
	private long origSystemReferenceId;
	private boolean updateStatusFlag;
	private int numWinners;
	private int numQual;
	private long tapProgramId;
	private int objectVersionNumber;
	private boolean catchAllFlag;
	private boolean namedAccountFlag;
	private boolean terrGroupFlag;
	private long terrGroupId;
	private long terrGroupAccountId;
}
